auth:
    path: /
    controller: App\Controller\AuthController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
trainings:
    path: /trainings
    controller: App\Controller\TrainingController::index
training:
    path: /training/{id}
    controller: App\Controller\TrainingController::show
    requirements:
        id: '\d+'
training_delete:
    path: /training_delete/{id}
    controller: App\Controller\TrainingController::delete
    requirements:
        id: '\d+'
exercise:
    path: /exercise/{id}
    controller: App\Controller\ExerciseController::index
    requirements:
        id: '\d+'
exercise_delete:
    path: /exercise_delete/{id}
    controller: App\Controller\ExerciseController::delete
    requirements:
        id: '\d+'
set:
    path: /sets
    controller: App\Controller\SetController::index
day:
    path: /day
    controller: App\Controller\DayController:index
day_started:
    path: /day_started/{training_id}/
    controller: App\Controller\DayController:started
    requirements:
        training_id: '\d+'
day_exercise:
    path: /day_exercise/{day_id}/{training_id}/{exrcise_id}/
    controller: App\Controller\DayController:exercise
    requirements:
        training_id: '\d+'
        exercise_id: '\d+'
        day_id: '\d+'
training_finish:
    path: /training_finish/{day_id}/
    controller: App\Controller\DayController:trainingFinish
    requirements:
        day_id: '\d+'
registration:
    path: /registration
    controller: App\Controller\RegistrationController:index
training_creator:
    path: /training/create
    controller: App\Controller\TrainingCreatorController:index
training_stats:
    path: /training/stats
    controller: App\Controller\TrainingStatController:index
exercise_list:
    path: /exercise/list
    controller: App\Controller\ExerciseController:ExerciseList
exercise_create:
    path: /exercise/create
    controller: App\Controller\ExerciseController:ExerciseCreate
add_exercise_to_training:
    path: /add_exercise_to_training/{ex_id}/{tr_id}/
    controller: App\Controller\TrainingController:addExerciseToTraining
    requirements:
        ex_id: '\d+'
        tr_id: '\d+'