auth:
    path: /
    controller: App\Controller\AuthController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
trainings:
    path: /trainings
    controller: App\Controller\TrainingController::index
training:
    path: /training/{id}
    controller: App\Controller\TrainingController::show
    requirements:
        id: '\d+'
exercise:
    path: /exercises/
    controller: App\Controller\ExerciseController::index
set:
    path: /sets
    controller: App\Controller\SetController::index