services:
    App\Controller\TrainingController:
        class: App\Controller\TrainingController
        arguments:
            - '@doctrine.orm.entity_manager'
    App\Controller\TrainingCreatorController:
        class: App\Controller\TrainingCreatorController
        arguments:
        - '@doctrine.orm.entity_manager'
    App\Controller\ExerciseController:
        class: App\Controller\ExerciseController
        arguments:
            - '@doctrine.orm.entity_manager'
    App\Controller\DayController:
        class: App\Controller\DayController
        arguments:
            - '@doctrine.orm.entity_manager'
