version: "2"
services:

    nginx:
      image: nginx:alpine
      container_name: nginx
      volumes:
          - ./logs:/var/log/nginx
          - ../:/var/www/html
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      links:
        - fpm

    fpm:
      build: phpdocker/php-fpm
      container_name: fpm
      volumes:
        - ../:/var/www/html
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      expose:
        - 9000
      links:
        - postgres

    postgres:
      image: postgres:9.6-alpine
      container_name: postgres
      volumes:
        - ./postgres/var/lib/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=root_my_trainer
        - POSTGRES_PASSWORD=er4ddJf4thfHHf34f77
        - POSTGRES_DB=my_trainer
      expose:
        - 5432

    tarantool:
        image: tarantool/tarantool:1.7
        container_name: trntl
        volumes:
          - ./tarantool:/opt/tarantool/
          - ./tarantool/var:/var/lib/tarantool
        environment:
          - TARANTOOL_USER_NAME=tarantool_my_trainer
          - TARANTOOL_USER_PASSWORD=er4ddJf4thfHHf34f77
        ports:
          - "3301:3301"
