App\Entity\Day:
  type: entity
  repositoryClass: App\Repository\DayRepository
  table: day
  id:
    day_id:
      type: integer
      generator: { strategy: IDENTITY }
  fields:
    creation_date:
      type: datetime
      nullable: false
    finish_date:
      type: datetime
      nullable: true
    main_time:
      type: string
      length: 40
      nullable: true
    deleted:
      type: boolean
      nullable: false
      options:
        default: false
  manyToOne:
    training_id:
      targetEntity: App\Entity\Training
      joinColumn:
        name: training_id
        referencedColumnName: training_id
        nullable: false
    user_id:
      targetEntity: App\Entity\User
      joinColumn:
        name: user_id
        referencedColumnName: user_id
        nullable: false