App\Entity\Training:
    type: entity
    repositoryClass: App\Repository\TrainingRepository
    table: training
    id:
        training_id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        training_name:
            type: string
            length: 256
        description:
            type: string
            length: 2056
        creation_date:
            type: datetime
        last_update_date:
            type: datetime
        deleted:
          type: boolean
          nullable: false
          options:
            default: false
    oneToMany:
        exercises:
          targetEntity: App\Entity\Exercise
          mappedBy: training_id
    manyToOne:
        user_id:
          targetEntity: App\Entity\User
          joinColumn:
            name: user_id
            referencedColumnName: user_id
            nullable: false