App\Entity\User:
    type: entity
    table: app_user
    id:
        user_id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        user_name:
            type: string
            length: 100
            unique: true
        password:
            type: string
            length: 254
        email:
            type: string
            length: 254
            unique: true
        is_active:
            type: boolean
        registration_date:
            type: datetime
        last_visit_date:
            type: datetime
    manyToOne:
        day_id:
            targetEntity: App\Entity\Day
            joinColumn:
                name: day_id
                referencedColumnName: day_id